### ISSUE TITLE
Suggestion: use cacheFile with sed

### ISSUE THREAD

**Issue by hathawaydave** [hexive/sunpaper#1]
In the function set_paper, $HOME is used with a path.  For example,

```sed -i s/./2/g $HOME/.cache/sunpaper.cache```

However, you already have a pointer to the full path:

```cacheFile=$HOME/.cache/sunpaper.cache```

I believe you could make the code easier to maintain/customize if you use the full path:

```sed -i s/./2/g $cacheFile```

This way, if a user wants to change where the cacheFile is, only one line need be changed.  For example, I use FILE=$XDG_CACHE_HOME/sunpaper/sunpaper.cache

I haven't yet downloaded the new function-based code, but this worked in the earlier version.

**Comment by hexive** [comment]
Thanks Dave!
