### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Rmdhn1** [hexive/sunpaper#14]
Does this support GIFs?

**Comment by hexive** [comment]
With a few small modifications you should be able to get gifs to work--nothing in this code base would prevent it.

The ogiri wallpaper switcher supports gifs so the easiest way would be to [enable Ogiri mode](https://github.com/hexive/sunpaper/wiki/Sway-Oguri-Mode) within sunpaper and then change the `.jpg` in line 467 to `.gif`
