### ISSUE TITLE
What are the guidelines for contributing wallpapers?

### ISSUE THREAD

**Issue by kirisoraa** [hexive/sunpaper#15]
Hi! I would like to draw a wallpaper to support most features of this project. What kinds of guidelines, files, rules etc should I (or someone else who would like to contribute) should follow?

**Comment by hexive** [comment]
Hey! Thanks for your interest--I'm eager to see what you come up with.

The most basic wallpaper set would require 8 images--with consecutive file names like 1.jpg, 2.jpg, 3jpg, etc. These would be displayed as follows:

    #1.jpg - after sunset until sunrise
    #2.jpg - sunrise for 15 min
    #3.jpg - 15 min after sunrise for 15 min
    #4.jpg - 30 min after sunrise for 1 hour
    #5.jpg - day light between sunrise and sunset events
    #6.jpg - 1.5 hours before sunset for 1 hour
    #7.jpg - 30 min before sunset for 15 min
    #8.jpg - 15 min before sunset for 15 min

If you want to support weather and moon phases it's a little more complicated. Take a look in /images/Corporate-Synergy/ to get a sense of how that looks. 

Weather requires those same 8 images in folders for /clear /rain /fog /storm (default view is cloudy).  /snow isn't supported yet but it's planned.

Moons require 8 more images in a /moons folder for night (1.jpg)  sunrise (2.jpg) and sunset (8.jpg) with the following addendums so it ends up looking like 1-1.jpg 1-2.jpg 1-3.jpg etc for each.

    # new -1
    # waxing crescent -2
    # first quarter -3
    # waxing gibbous -4
    # full -5
    # waning gibbous -6
    # last quarter -7
    # waning crescent -8

I hope this helps. Please followup with any specific questions you have along the way.

**Comment by hexive** [comment]
I know this is quite old -- but I'm refreshing sunpaper with some new content and I was curious if you ever ended up making a set of timed wallpapers for yourself.

**Comment by kirisoraa** [comment]
@hexive I ended up not getting much farther than the planning phase due to some circumstances. Since then I've created a custom setup using pywal :p 
so, many apologies, but I don't have anything to contribute to this project right now, no matter how cool it is. maybe in the future :D

**Comment by Serg10** [comment]
Hello! I am planning to make a python script for gimp that automates the process of creating complex wallpapers (with, moons, weather,...) following the image structure of images/Corporate-Synergy/, the idea is to give the script the base images and different layers of the moons and weather and automatically generate the folder structure, images and file names.
I will inform you ;)

**Comment by hexive** [comment]
@Serg10 - this sounds like a great idea. Please let me know if you end up with a script that you'd like to share and/or some cool new wallpapers!
