### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jevy** [hexive/sunpaper#16]
Hi there!

I'm packaging this up for Nix but I have to mark it as `unfree` unless there is a license included in the upstream package. Would that me something you could add?

Ref: https://github.com/NixOS/nixpkgs/pull/174156#discussion_r885125600

Jevin

**Comment by hexive** [comment]
I might need some guidance on this -- I'm happy to add a license for the code but there are 3rd party images in the repo that I don't hold copyright on. I assume that license cannot apply to them. Any direction would be appreciated.

**Comment by jevy** [comment]
Howdy! For context, `sunpaper` is my first effort to get a nixpkg in the repo. After I [get my PR approved](https://github.com/NixOS/nixpkgs/pull/174156), I'll get it into `home-manager` to make it easy for users to get sunpaper with a one liner 😍.

You would just have to add one of the classic `LICEE` files in the top level git dir that is one of the free FOSS ones. The only tricky thing would be having explicit permission that the images from the artists conform to a license you suggest. [Github has this information](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) that leads to [choosealicense.com](https://choosealicense.com/no-permission/#for-users)

**Comment by hexive** [comment]
Thank you for your help and patience with this one. I'm not a lawyer and this stuff is confusing.

Merged the pull request and closing with commit b48c0fc0e1a51b7e3784d7fb35cf3e087dbef873
