### ISSUE TITLE
Support swww

### ISSUE THREAD

**Issue by Nil0375** [hexive/sunpaper#18]
oguri is out of maintenance
Can you provide support for swww?

**Comment by hexive** [comment]
Thanks for letting me know about the swww project. It looks promising. It should be straight forward to add.

**Comment by hexive** [comment]
swww integration is in sunpaper now with commit 5f397aa03bfd2ff209fee3a1d9df49b0ad279388

swww is pretty great and this now provides straight forward and simple transition animations. thanks again for your suggestion.
