### ISSUE TITLE
Wiki - Basic Configuration - Update for non-yanks ;)

### ISSUE THREAD

**Issue by tfwiii** [hexive/sunpaper#19]
Basic Configuration

Set your latitude and longitude for your current location. If you aren't sure you can get these numbers from places like [latlong.net](https://www.latlong.net/) or even google maps.

Make sure your latitude number ends with N **or S**
latitude="38.9072N"

and longitude ends with W **or E**
longitude="77.0369W"

**Comment by hexive** [comment]
Many thanks! This change is in:
https://github.com/hexive/sunpaper/wiki/Configure
