### ISSUE TITLE
Suggestion: Add a configuration file

### ISSUE THREAD

**Issue by jso8910** [hexive/sunpaper#3]
I don't think this exists but please do this. I am maintaining a fork of this because I have my configs in a repository and merging it was hell (I probably messed something up but who knows). Please allow us to put a config in `~/.config/sunpaper/config` or `~/.config/sunpaper.conf` or whatever. Anyways I wanna be able to delete the fork.

**Comment by jso8910** [comment]
Made PR #4

**Comment by hexive** [comment]
I can see where an external configuration file would be useful -- I like it.

I'm not sure I want to move everyone to use it by default, though. I'm trying to keep things as simple as possible and that would mean a new user would have to first run the script to generate the config, and then edit the config, etc. +1 step.

Maybe it doesn't matter, but I want to think about it.

But for now I'll push a simple if config file exists then source it line that we can both use and we'll call it an experimental feature. haha

It'll look for config at:
~/.config/sunpaper/config

Please let me know if you have any issues with it. And obviously please check for new config settings whenever you update the script.

**Comment by jso8910** [comment]
I think that having a default config file would be good but since this isn't a package i couldn't think of a way to make it. I personally think that the way I have it now works well because if you don't want to touch configs (other than longitude and latitude) you don't have to. The issue with the current system is it is really hard to keep the script up to date whilst also having your own location and settings. Having settings in the script isn't the best UX. If you can think of a way to easily automatically generate the config file before the script is run I would be glad to hear it but I can't think of one.
