### ISSUE TITLE
Ubuntu fail: setwallpaper not found, isn't an apt or snap I can install

### ISSUE THREAD

**Issue by dginovker** [hexive/sunpaper#5]
On first run I was getting this error:

![image](https://user-images.githubusercontent.com/32943174/111665076-ce67be80-87e8-11eb-9476-308b865340f0.png)

But I was able to resolve it with `snap install sunwait`. Unfortunately, there's no `setwallpaper` I can install on Ubuntu.

**Comment by hexive** [comment]
Yes, `sunwait` and `wallutils` (for `setwallpaper`) are dependencies for sunpaper  
[https://github.com/hexive/sunpaper/wiki/Install](https://github.com/hexive/sunpaper/wiki/Install)

wallutils has pretty good documentation for installing on ubuntu  
[https://github.com/xyproto/wallutils#ubuntu](https://github.com/xyproto/wallutils#ubuntu)

And if you go their suggested route of first installing go, you can then install `setwallpaper` with:
`go get -u github.com/xyproto/wallutils/cmd/setwallpaper`

https://github.com/hexive/sunpaper/wiki/Creative-Uses#building-wallutil-dependency

**Comment by dginovker** [comment]
I have no idea how I missed that in the setup.
