### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [hexive/sunpaper#8]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Sunpaper on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by hexive** [comment]
Thank you for the suggestion. I'm not sure that sunpaper in its current form is a good fit for flatpak. I think most flatpak users would expect something that just works out-of-the-box after install. As of now, sunpaper has a pretty convoluted and confusing configuration that requires manual edits and it's also not so straight forward to automate. If this project ever evolves into a proper daemon with gui configuration I'll definitely give flatpak a look for distribution.
