### ISSUE TITLE
currentWeather alwas equals cloud when using -s

### ISSUE THREAD

**Issue by BraveSentry** [hexive/sunpaper#9]
I was trying out the weather functionality with a vanilla sunpaper.sh to which I only made the following changes: `weather_enable=true`, added my coordinates, my weather api key and my city code, all of which seem to work. Nonetheless, I get no change of wallpaper when testing with, for example `/path/to/sunpaper.sh -s Storm`
I added `-x` to the first line of sunpaper.sh, and the output is this:

```
+ latitude=51.3072N
+ longitude=40.0369E
+ wallpaperPath=/home/me/sunpaper/images/Corporate-Synergy
+ wallpaperMode=scale
+ cachePath=/home/me/.cache
+ moonphase_enable=false
+ weather_enable=true
+ weather_api_key=[my key]
+ weather_city_id=[my city]
+ darkmode_enable=false
+ darkmode_run_day=
+ darkmode_run_night=
+ pywalmode_enable=false
+ pywal_options=
+ pywal_options_day=
+ pywal_options_night=
+ pywal_image_day=true
+ pywal_image_night=true
+ status_icon=
+ oguri_enable=false
+ oguri_config=/home/me/.config/oguri/config
+ wallpaperModeOguri=fill
+ version=3.17
+ CONFIG_FILE=/home/me/.config/sunpaper/config
+ '[' -f /home/me/.config/sunpaper/config ']'
++ sed 's:/*$::'
++ echo /home/me/sunpaper/images/Corporate-Synergy
+ wallpaperPath=/home/me/sunpaper/images/Corporate-Synergy
++ echo /home/me/.cache
++ sed 's:/*$::'
+ cachePath=/home/me/.cache
+ cacheFileWall=/home/me/.cache/sunpaper_cache.wallpaper
+ cacheFileDay=/home/me/.cache/sunpaper_cache.day
+ cacheFileNight=/home/me/.cache/sunpaper_cache.night
+ cacheFileWeather=/home/me/.cache/sunpaper_cache.weather
+ :
+ case $1 in
+ '[' Storm ']'
+ test_weather=Storm
+ shift
+ shift
+ :
+ case $1 in
+ break
+ get_currenttime
+ '[' '' ']'
++ date +%s
+ currenttime=1616922382
+ get_suntimes
++ sunwait list civil rise 51.3072N 40.0369E
+ get_sunrise=05:33
++ sunwait list civil set 51.3072N 40.0369E
+ get_sunset=19:17
++ date -d 05:33 +%s
+ sunrise=1616902380
++ date -d '05:33 15 minutes' +%s
+ sunriseMid=1616903280
++ date -d '05:33 30 minutes' +%s
+ sunriseLate=1616904180
++ date -d '05:33 90 minutes' +%s
+ dayLight=1616907780
++ date -d '19:17 90 minutes ago' +%s
+ twilightEarly=1616946420
++ date -d '19:17 30 minutes ago' +%s
+ twilightMid=1616950020
++ date -d '19:17 15 minutes ago' +%s
+ twilightLate=1616950920
++ date -d 19:17 +%s
+ sunset=1616951820
+ set_cache
+ '[' -f /home/me/.cache/sunpaper_cache.wallpaper ']'
+ touch /home/me/.cache/sunpaper_cache.wallpaper
+ echo 0
+ currentpaper=0
+ [[ true == \t\r\u\e ]]
+ check_weather
+ '[' -f /home/me/.cache/sunpaper_cache.weather ']'
+ get_weather
+ weather_info=
+ weather_main=
+ weather_url='http://api.openweathermap.org/data/2.5/weather?id=[my city]&appid=[my key]&units=Imperial'
+ '[' Storm ']'
+ weather_main=Storm
+ [[ Storm = '' ]]
+ [[ Storm = *Rain* ]]
+ [[ Storm = *Drizzle* ]]
+ [[ Storm = *Mist* ]]
+ [[ Storm = *Thunderstorm* ]]
+ [[ Storm = *Extreme* ]]
+ [[ Storm = *Squall* ]]
+ [[ Storm = *Tornado* ]]
+ [[ Storm = *Clear* ]]
+ [[ Storm = *Fog* ]]
+ [[ Storm = *Haze* ]]
+ [[ Storm = *Smoke* ]]
+ [[ Storm = *Dust* ]]
+ [[ Storm = *Sand* ]]
+ [[ Storm = *Ash* ]]
+ currentWeather=cloud
+ touch /home/me/.cache/sunpaper_cache.weather
+ echo cloud
+ set_paper
+ '[' 1616922382 -ge 1616902380 ']'
+ '[' 1616922382 -lt 1616903280 ']'
+ '[' 1616922382 -ge 1616903280 ']'
+ '[' 1616922382 -lt 1616904180 ']'
+ '[' 1616922382 -ge 1616904180 ']'
+ '[' 1616922382 -lt 1616907780 ']'
+ '[' 1616922382 -ge 1616907780 ']'
+ '[' 1616922382 -lt 1616946420 ']'
+ [[ 0 != 5 ]]
+ image=5
+ sed -i s/./5/g /home/me/.cache/sunpaper_cache.wallpaper
+ setpaper_construct
+ [[ true == \t\r\u\e ]]
+ [[ /home/me/sunpaper/images/Corporate-Synergy == *\C\o\r\p\o\r\a\t\e\-\S\y\n\e\r\g\y* ]]
+ [[ -z x ]]
+ [[ cloud == \c\l\o\u\d ]]
+ true
+ '[' false == true ']'
+ '[' false == true ']'
+ setwallpaper -m scale /home/me/sunpaper/images/Corporate-Synergy/5.jpg
+ [[ false == \t\r\u\e ]]
+ '[' false == true ']'
+ '[' '' == true ']'

```
Despite the testing parameter, `currentWeather` still equals cloud. I suspect this is the error.

I then tried to see whether this would apply in real life too, so I changed my city ID to Minsk to check against rain and then to Lagos to check for clear skies, and both worked. So this seems to be a strictly testing related issue.

Also, on a related note that may or may not warrant a separate issue: When using moon phases and/or weather, would it be possible to remove the check for the corporate synergy theme and instead check for a correctly named subfolder and file within `wallPaperPath`? As is, it's difficult to make ones own weather-dependent set of wallpapers.

**Comment by hexive** [comment]
Does `sunpaper.sh -s Thunderstorm` work for you? What about the other weather flags Clear | Clouds | Rain | Fog (note these are case sensitive)

Do you remember where you saw the suggestion for `sunpaper.sh -s Storm`? I'd want to correct that if it's in the docs somewhere.

**Comment by hexive** [comment]
> When using moon phases and/or weather, would it be possible to remove the check for the corporate synergy theme and instead check for a correctly named subfolder and file within wallPaperPath? As is, it's difficult to make ones own weather-dependent set of wallpapers.

This is a great suggestion and I'll get it in for the next update.

**Comment by BraveSentry** [comment]
Thanks for the quick response! I think this all was a bad combination of reading it in the wiki, my brain sayin "ah, it's all the folder names, just in upper case, you can remember that and close the window", this not working due to me having set my folder with fjord pictures and not corp. synergy and then me testing it only with "Storm". Although this is my fault, I still have to ask: Is there any particular reason to not have the arguments consistent with the folder names? If not I'd suggest adding them as possible conditions:

```
        if [[ "$weather_main" = *rain* ]] || [[ "$weather_main" = *Rain* ]] || [[ "${weather_main}" = *Drizzle* ]] || [[ "$weather_main" = *Mist* ]]; then
            currentWeather="rain"

        elif [[ "$weather_main" = *storm* ]] || [[ "$weather_main" = *Thunderstorm* ]] || [[ "$weather_main" = *Extreme* ]] || [[ "$weather_main" = *Squall* ]] || [[ "$weather_main" = *Tornado* ]]; then
            currentWeather="storm"

        elif [[ "$weather_main" = *clear* ]] || [[ "$weather_main" = *Clear* ]]; then
            currentWeather="clear"

        elif [[ "$weather_main" = *fog* ]] || [[ "$weather_main" = *Fog* ]] || [[ "$weather_main" = *Haze* ]] || [[ "$weather_main" = *Smoke* ]] || [[ "$weather_main" = *Dust* ]] || [[ "$weather_main" = *Sand* ]] || [[ "$weather_main" = *Ash* ]]; then
            currentWeather="fog"

        else
            currentWeather="cloud"

        fi
```

**Comment by hexive** [comment]
The testing flag names are the same as what comes out of the weather API. That was useful to me early on to make sure the IF logic was going to work for all the API conditions. 

And I probably wasn't thinking about any of that when I named the storm folder ;) Unfortunately renaming that folder would be a breaking change that probably isn't worth it.

The whole --sky testing method is also pretty user unfriendly at this point and could probably be reworked to not be case sensitive, include substring names like "storm" and even automatically clear the cache so you don't have to do that manually.

**Comment by hexive** [comment]
Oh, also, if you end up with a cool new weather/moon theme ... I'd absolutely like to see how that turns out. If you like -- please send me a note here or reddit with your results.

**Comment by hexive** [comment]
Thank you again for your suggestion to not use theme names for weather/moon to allow for easier use of custom made themes. That's in now and so I'll close this thread.
